### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by erasche** [usegalaxy-eu/vgcn#13]
@sj213 @bgruening if anyone has some nice ideas for new names; no one we tell about 'vgcn' can seem to remember that acronym. So we could use a catchier name, maybe more galaxy related too?

A couple of ideas:

**Hyades**
> it consists of a roughly spherical group of hundreds of stars sharing the same age, place of origin, chemical characteristics, and motion through space.

**DysonSphere**
Given that they're designed as 100s of identical units which face a sun that collect energy/"data" from the sun?

**VGCN**
Don't rename it because we're happy with it.

**Comment by bgruening** [comment]
Hehe, the new names are not easier to remember, but way more fancier :)

Thanks for bringing them up - I will also think about it.

**Comment by bgruening** [comment]
I'm in favor of "hyades" if we really need to change it. `vgcn` is actually a name that you can google and you find us :)

**Comment by erasche** [comment]
> is actually a name that you can google and you find us

yeah, this is a fair point!

But getting people to remember those letters in the correct order seems difficult. Both of our guests that one week whenever it was brought up called it vcn/gcn/vncg/every other combination of letters. That's the part I guess I'm worried about. We do not strictly *need* to rename this, just want to make sure it is memorable for our users. If your vote is "don't rename", that's valid too.

**Comment by sj213** [comment]
Hm, "Dyson Sphere" is a bit long (and cumbersome to pronounce as well, unless you slur it into an unrecognizeable sequence of sounds) not sure that this really has a chance of catching on.

As for "Hyades": that's a nice one indeed, but I don't think it will be much easier to remember than "vgcn" (I had to go and look it up in RE...[1])

If we want a name that it catchy and somehow evokes the term "Galaxy", maybe we could look in the namespace of the parallel universe of "Star Trek" or, better yet, "Babylon 5" ;) - though I can't think of sth suitable OTTOMH; "Hyperion", "Starfury" or "Jumpgate" probably isn't quite the thing...

OTOH, personally I'm fine with "vgcn" - it is short and indicates what it does.

Just my EUR 0.02...

[1] RE = "Paulys Realencyklopaedie der classischen Altertumswissenschaft"

**Comment by erasche** [comment]
In that case, closing. Thanks y'all

**Comment by sj213** [comment]
Just had a second thought crossing my mind: if you want something potentially catchy and related to "Galaxy", what about "MSB" for "Medium-Sized Bang"? (Because the deployment system could be used to create, among conceivably other things, a large number of Galaxies `;)`

**Comment by erasche** [comment]
Yeah, I get the idea but in english that has unnecessary connotations. Something along 'stellar nursery' would be more neutral, but the wrong part of the process, that would be our build infra, not the output result (galactic objects). Ah well, I guess nothing is perfect, was just hoping for something more memorable with better branding.

**Comment by sj213** [comment]
Really! Who'd a thunk Fred Hoyle was such a rascal after all. Can't them astronomers ever think of the children! `*g*`
