### ISSUE TITLE
Centos8 lacks libnsl

### ISSUE THREAD

**Issue by gmauro** [usegalaxy-eu/vgcn#28]
centos@vgcnbwc-worker-c40m2-9548:~$ ldd  /usr/local/tools/_conda/envs/mulled-v1-e7321ba46fa5ea4c6b9a06b78e6cd5182b33c0a47c2c86b5d610e1361f8b1686/bin/perl
    linux-vdso.so.1 (0x00007ffd0fdc5000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007febcba93000)
    libnsl.so.1 => not found
    libdl.so.2 => /lib64/libdl.so.2 (0x00007febcb88f000)
    libm.so.6 => /lib64/libm.so.6 (0x00007febcb50d000)
    libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007febcb2e4000)
    libutil.so.1 => /lib64/libutil.so.1 (0x00007febcb0e0000)
    libc.so.6 => /lib64/libc.so.6 (0x00007febcad1d000)
    /lib64/ld-linux-x86-64.so.2 (0x00007febcbcb3000)

**Comment by bgruening** [comment]
This reminds me that we have also installed font libraries on those old workers. Is that still included?

**Comment by gmauro** [comment]
Do you mean this:
https://github.com/usegalaxy-eu/vgcn/blob/495f8c33c4b0f3daa2b319a962089a252a8590ed/ansible-roles/basic/tasks/main.yml#L25
