### ISSUE TITLE
Limit max file size

### ISSUE THREAD

**Issue by sj213** [usegalaxy-eu/vgcn#41]
We should limit the max file size for **all** jobs, to mitigate the impact of runaway log files etc. The easiest way to do this is to set an ulimit capping (`RLIMIT_FSIZE`, see `getrlimit(2)`) on the HTCondor master on the worker nodes, whence it will be passed down to the startd and the jobs eventually. We could create a file `/etc/systemd/system/condor.service.d/ulimit-fsize.conf` containing

```
[Service]
LimitFSIZE=268435456000
```

assuming a generous limit of 250 GiB.

The file should of course be created from a template and the limit should be configurable via group vars. I am however unsure where exactly this should be placed in the `vgcn` playbooks.

**Comment by bgruening** [comment]
@mtangaro do you have any preference here?

**Comment by sj213** [comment]
Commenting on my own proposal: we should probably set a hard limit that is higher than the soft limit, so that the latter can be raised for some job types. The syntax *soft_limit*`:`*hard_limit* also works in systemd. I just tested the following on one idle mothur compute node and it worked:

```
[Service]
LimitFSIZE=268435456000:1073741824000
```

**Comment by bgruening** [comment]
@sj213  has created https://github.com/usegalaxy-eu/ansible-fslimit we just need to get it into the VGCN.

**Comment by mira-miracoli** [comment]
We integrated this, closing the issue :)
