### ISSUE TITLE
Firewall off metadata unless root

### ISSUE THREAD

**Issue by hexylena** [usegalaxy-eu/vgcn#9]
https://serverfault.com/questions/436086/how-to-prevent-firewall-calls-to-aws-ec2-instance-metadata-api

In general the only thing running on this *should* be galaxy jobs (you shouldn't be running arbitrary user jobs in here), and those *shouldn't* have any issues whereby they can request the metadata IP address, but just in case...

**Comment by mira-miracoli** [comment]
we turned it on again, hoping that it works :D
